### PR TITLE
Upgrading dependencies

### PR DESCRIPTION
**Pull request by backmeupplz**
Came across this npm module, decided to help upgrading the dependencies. Cheers!

### CODE REVIEW

**Comment by steebchen** [comment]
Thanks! Can you confirm everything works as usual with your update? I don't use this module anymore, so it would be great if you could assure that everything works the same.

**Comment by backmeupplz** [comment]
@steebchen yep, just used my fork in https://github.com/backmeupplz/telegram-sticker-starter

**Comment by backmeupplz** [comment]
tbh, had to do this because `smart-promisify` didn't want to return 1.0.2 version and `yarn install` halted.

**Comment by steebchen** [comment]
Alright, thanks!

**Pull request merged**
